---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dagger-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Applications
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagger-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dagger-runners
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/matipan/dynamic-dagger-engines
    targetRevision: main
    path: argocd/dagger-runners/
  destination:
    server: https://kubernetes.default.svc
    namespace: dagger-runners
