apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: dagger-runners
  namespace: dagger-runners
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: dynamic-dagger-engines-guide

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: dynamic-dagger-engines-guide

  instanceProfile: eksctl-KarpenterNodeInstanceProfile-dynamic-dagger-engines-guide

  amiSelectorTerms:

  # Configure `/var/lib/dagger` to be an explicit filesystem. 
  # This optimizes dagger engine runs by not relying on overlay-fs for the 
  # disk-heavy operations that the dagger engine does through buildkit
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    sudo mkfs -t xfs /dev/nvme1n1
    sudo mkdir /var/lib/dagger
    sudo mount /dev/nvme1n1 /var/lib/dagger

    --BOUNDARY--

  tags:
    node-for: dagger-runners

  # TODO: configure disk volumes that are reasonable for your usage
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 200Gi
      volumeType: gp3


  detailedMonitoring: true
